# redirect to https
[http.middlewares.redirect_to_https]
[http.middlewares.redirect_to_https.redirectscheme]
scheme = "https"

[http.middlewares.escience_ips_only.ipWhiteList]
sourceRange = ["127.0.0.1", "172.17.0.0/24"]
